import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import DecorativeBackground from "@/components/DecorativeBackground";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Subhendu Jena",
  description: "Generated by Subhendu",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative flex items-center justify-center w-full z-50">
          <Navbar />
        </div>
        <div className="bg-white dark:bg-black z-10 dark:text-white mt-16">
          {children}
        </div>
        <div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
